# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdPair',
            fields=[
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('udn_id', models.CharField(blank=True, max_length=36, null=True, unique=True)),
            ],
        ),
    ]
